### ISSUE TITLE
Local image builds (w/o `--publish`) should use local images when remote images are not available

### ISSUE THREAD

**Issue by sclevine** [buildpacks/roadmap#44] opened 2019-01-27 20:28 UTC
**Acceptance Criteria**
*Case #1*
**When** I build an image with `pack build my-image`
**And** A remote copy of:
- The builder or
- The associated run image
is not available
**And** A local copy of the image is available
**Then** The local copy is silently used for the build

*Case #2*
**When** I build an image with `pack build my-image`
**And** A remote copy of:
- The builder or
- The associated run image
**is** available
**And** A local copy of the image is available
**Then** The remote copy of the image is pulled and used for the build

**Comment by ekcasey** [comment] 2019-01-28 15:34
duplicate of https://github.com/buildpack/pack/issues/90, closing

**Closed as completed by ekcasey** 2019-01-28 15:34 UTC
Labels: bug
